### ISSUE TITLE
Router Choice.

### ISSUE THREAD

**Issue by paradoxewan** [Keplerjs/Kepler#6]
Is there a reason for using Iron over flow router?

**Comment by stefanocudini** [comment]
Hi @paradoxewan,
the only reason is that when I startedthis project flow-router did not exist!
I would like to migrate to some other router as soon as possible because this has some problems that have been resolved with bad hacks.

However I seen that kadirahq has left the meteor projects.. https://kadira.io/
then I don't know what could be the alternative today. If you have any suggestion I'm ready to work together to update this part.

In fact for this I maintain configurations of the router in only one file:
https://github.com/Keplerjs/Kepler/blob/master/packages/keplerjs-core/client/router.js
so it is simply making an migration without conflicts

**Comment by stefanocudini** [comment]
https://trello.com/c/k6DgCgtc/45-change-router
